version: '3'

services:
  scsb-sftp:
    image: atmoz/sftp
    volumes:
        - ./ssh_keys/ssh_host_ed25519_key:/etc/ssh/ssh_host_ed25519_key
        - ./ssh_keys/ssh_host_rsa_key:/etc/ssh/ssh_host_rsa_key
        - ./data/solr-data:/home/recap/upload
        - ~/.ssh/id_rsa.pub:/home/recap/.ssh/keys/id_rsa.pub:ro
    ports:
        - "2222:22"
    command: recap::1001
  scsb-mysql:
    build: ../docker/scsb-mysql/
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  scsb-activemq:
    build: ../docker/scsb-activemq/
    depends_on:
      - scsb-mysql
    ports:
      - "8162:8161"
      - "61616:61616"
      - "1099:1099"
    environment:
      - "DB_URL=jdbc:mysql://scsb-mysql:3306/recapactivemq?relaxAutoCommit=true"
      - "DB_USERNAME=recap"
      - "DB_PASSWORD=recap"
      - "USERS=admin: admin, admin"
  scsb-solr-server:
    build: ../docker/scsb-solr-server
    depends_on:
      - scsb-mysql
    ports:
      - "8984:8983"
    volumes:
      - ../data/solr-data:/var/data/solr
    environment:
      - "ENV=-m 4g"
  scsb-solr-client:
    build: ../docker/scsb-solr-client
    depends_on:
      - scsb-mysql
      - scsb-solr-server
      - scsb-activemq
    ports:
      - "9094:9093"
    volumes:
      - ../data:/recap-vol
    environment:
      - "ENV=-XX:+HeapDumpOnOutOfMemoryError -Dspring.profiles.active=local-container -Dspring.config.location=/recap-vol/config/application.properties -Djsse.enableSNIExtension=false -Dorg.apache.activemq.SERIALIZABLE_PACKAGES=''"


#  web:
#    build: .
#    command: python manage.py runserver 0.0.0.0:8000
#    volumes:
#      - .:/code
#    ports:
#      - "8000:8000"
#    depends_on:
#      - db
