version: '3.7'

services:
  scsb-oauth:
    image: newthings/google-oauth-mock
    ports:
        - "8077:8077"
    environment:
      - "OAUTH2_DISABLE_CONSENT=true"
      - "AUTHORIZED_REDIRECT_URL=http://localhost:9091"
  scsb-sftp:
    image: atmoz/sftp
    volumes:
        - ./data/config/ssh_keys/id_rsa.pub:/home/recap/.ssh/keys/id_rsa.pub:ro
        - ./data/sftp-data:/home/recap/upload
    ports:
        - "2222:22"
    command: recap::1001
  scsb-mysql:
    build: ../recap-docker/scsb-mysql/
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      start_period: 20s
  scsb-activemq:
    build: ../recap-docker/scsb-activemq/
    depends_on:
      - scsb-mysql
    ports:
      - "8162:8161"
      - "61616:61616"
      - "1099:1099"
    environment:
      - "DB_URL=jdbc:mysql://localhost:3307/recapactivemq?relaxAutoCommit=true"
      - "DB_USERNAME=recap"
      - "DB_PASSWORD=recap"
      - "USERS=admin: admin, admin"
      - "ENV=-Dscsb.batch.schedule.url=http://localhost:9096/ -Dorg.apache.activemq.SERIALIZABLE_PACKAGES=*"

  scsb-solr-server:
    build: ../recap-docker/scsb-solr-server
    depends_on:
      - scsb-mysql
    ports:
      - "8984:8983"
    volumes:
      - ./data/solr-data:/var/data/solr
    environment:
      - "ENV=-m 4g"
  scsb-solr-client:
    build:
      context: ../recap-docker/scsb-solr-client
      args:
        repo_owner: sartography
        repo_name: recap-scsb-solr-client
        # repo_tag: v1.3.2
    depends_on:
      - scsb-mysql
      - scsb-solr-server
      - scsb-activemq
    ports:
      - "9090:9090"
    volumes:
      - ./data:/recap-vol
    environment:
      - "ENV=-XX:+HeapDumpOnOutOfMemoryError -Dspring.profiles.active=local-container -Dspring.config.location=/recap-vol/config/scsb-solr-client.application.properties -Djsse.enableSNIExtension=false -Dorg.apache.activemq.SERIALIZABLE_PACKAGES=*"
